### ISSUE TITLE
Add support for the "Insanity" layer

### ISSUE THREAD

**Issue by brollb** [brollb/cnn-creator#50]
The CASIA network architecture prototxt ([here](https://github.com/happynear/FaceVerification/blob/master/caffe_proto/CASIA_train_test.prototxt)) uses a layer called "Insanity" which is currently unsupported.

**Comment by brollb** [comment]
I am leaning against this actually bc it looks like it is just available in the given fork of Caffe...

**Comment by JimnyCricket** [comment]
Yes, Insanity layer is a fork of Caffe.

**Comment by brollb** [comment]
This is not a priority right now
